### ISSUE TITLE
vagrant-centos7-k8s-kubeedge question

### ISSUE THREAD

**Issue by yz271544** [Poorunga/edgemesh#5]
as you can see, i  use vagrant + centos7 + k8s + kubeedge to build my environment.

## Q1 
The virtual machine environment built by Vagrant is different from that of VMware. ETH0 is used for NAT network communication, and the hostonly network built by ETH1 is needed for in-cluster communication.

If I use Flannel + CNI, I can modify the configuration of Flannel.  Make edge-node docker0 bridged to eth1.
```yaml
  containers:
  - name: kube-flannel
    image: quay.io/coreos/flannel:v0.10.0-amd64
    command:
    - /opt/bin/flanneld
    args:
    - --ip-masq
    - --kube-subnet-mgr
    - --iface=eth1                    # like this
```
How do this with Edgemesh? 

## Q2
Should the Edge node config of /etc/resolve. conf ?
